brew "atuin"
brew "autojump"
brew "chezmoi"
brew "tmux"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

cask "alacritty"
cask "google-chrome"
cask "karabiner-elements"
cask "keepassxc"
cask "maccy"
cask "microsoft-edge"
cask "obs"
cask "utm"
cask "visual-studio-code"
