https://www.reddit.com/r/socialmedia/comments/10z01nv/best_social_media_listening_tools/:
  text: |
    Best Social Media Listening Tools
    Professional Discussion
    I kinda feel like social media listening tools in the market are popping up in the market everyday & demand is also increasing. These are my favourite tools for social listening:

    1. Mention
    It’s one of the most used social listening tool as I always come across this tool in a conversation about social listening.

    Overall the tool is recommended by me because the resources & features they provide can help you better than other tools in the market.

    2. Brandwatch
    Brandwatch is a social media management tool, but they acquired Falcon, A social listening tool. Now, it’s the part of their platform and you can schedule & listen to your audience within their platform.

    One of the reasons I recommend them is they do great job at CX & collaborate well with HigherEd. If you work in HigherEd, I will recommend you to go for Brandwatch.

    3. Syften
    Syften can help you track conversations around your product & business on reddit, quora, hacker news & others.

    I don’t dislike the tool, but it’s best for SaaS owners, startups. It’s a scrappy social listening tool but it works. That’s why I mentioned it here.

    4. Brand 24
    Brand 24 is another great social listening tool with a better reporting process. You can track mentions across all main marketing channels & get reported.

    I myself came across brand24 recently through reddit suggestions. From what I have heard so far. It deserves to be here.

    5. Tweetdeck
    It’s the best tool to track conversations around your brand on Twitter.

    But some features like reporting & better CX isn’t the best part of Tweetdeck. As Twitter isn’t fully focused on users utilising this feature.

    But if your brand audience is active on twitter, this tool can deliver most accurate results.

    6. Gummy Search
    It’s one of the best tool to track conversations across reddit & you can also get analysis of sub-reddits where your target audience is active.

    Recommended to SaaS founders, startups & entrepreneurs to track conversations around their business.

    Honourable mentions
    Agorapulse & Sproutsocial are also famous for social listening but they are overall social media management tools. That’s why you might consider moving to them completely if your current tool lacks social listening features.

    Awario is a social listening tool with similar features to tools mentioned above but not a standout. That’s why it didn’t make the list.

    Google Alerts is one of my favourites but the tracking is limited to Google only.

    Thanks for reading. You can share your favourite social listening tool below & join r/marketingcurated for more tools & resource suggestions.
  threshold: 0.5856844186782838
https://www.reddit.com/r/mac/comments/13d9rfd/monitoring_plist_changes_and_generating/:
  text: |
    Monitoring plist changes and generating `PlistBuddy` commands
    Question
    I am looking for a tool or method to monitor plist changes on my Mac and generate the corresponding PlistBuddy commands when preferences are changed in macOS or apps. I want to avoid using defaults write since some preference values are nested. (Plists are like onions, they have layers upon layers, and just when you think you've peeled them all, another one appears to make you cry.)

    I've found these repositories, but they don't exactly do what I want:

    macos-defaults

    plistwatch

    My ideal workflow is as follows:

    Start the monitoring tool.

    Change preferences in macOS or apps.

    The tool shows PlistBuddy commands.

    Copy and paste the commands into my setup script.

    This would be similar to how Karabiner-EventViewer works for a different problem.

    Any suggestions on how to achieve this or existing tools that can help me with this workflow?
  threshold: 0.3411819338798524
https://www.reddit.com/r/selfhosted/comments/13tkasa/seeking_advice_on_developing_a_selfhosted_tool/:
  text: |
    Seeking advice on developing a self-hosted tool for monitoring and notifying users of relevant social media comments
    Hello r/selfhosted community,

    I'm about to embark on a journey of self-loathing, er, self-hosting, and I could use your advice. I'm working on a tool that monitors and notifies users of relevant social media comments related to a specific product using natural language processing and machine learning techniques. The draft of the documentation is available here.

    "Self-hosting? More like self-loathing because it's like being your own customer service representative, except the customer is an idiot, and that idiot is you." But I'm willing to take on the challenge because I want to ensure the tool is suitable for self-hosting and offers the flexibility and control that comes with it.

    Some of the challenges I'm facing include:

    Ensuring the tool can effectively monitor and analyze comments across various social media platforms.

    Handling potential false positives or negatives in the comment analysis.

    Designing an efficient notification system for users.

    I've recently posted a question on r/LanguageTechnology. However, that post is focused on NLP, and I'd like to shift the focus here to self-hosting aspects.

    I would appreciate any feedback, suggestions, or recommendations from the r/selfhosted community on the self-hosting aspects of this project. Are there any specific aspects you'd like to discuss or any additional features you think would be valuable for this tool?

    Thank you for your time and input!
  threshold: 0.6040834188461305
https://www.reddit.com/r/LanguageTechnology/comments/13sqmks/seeking_advice_on_developing_a_tool_to_monitor/:
  text: |
    Seeking Advice on Developing a Tool to Monitor and Notify Users of Relevant Social Media Comments
    I have been working on a tool that aims to monitor and notify users of relevant social media comments related to a specific product. I have documented my thoughts and ideas for this tool in this GitHub repository. The tool uses natural language processing and machine learning techniques to find and notify users of similar Reddit posts.

    I would like to ask for advice on the following aspects:

    Are there any existing tools or approaches that can help me with this task, or if there are any suggestions for how to effectively use NLP and machine learning techniques for this purpose?

    Any insights or resources related to NLP and machine learning in the context of social media monitoring would be greatly appreciated.

    They say NLP can predict our behavior. If only it could predict my next terrible joke, I'd save so much embarrassment.

    Please feel free to review the documentation and provide any feedback or suggestions. Thank you!
  threshold: 0.5617572069168092
https://www.reddit.com/r/chrome_extensions/comments/15074p2/how_do_you_install_configure_and_detect_changes/:
  text: |
    How do you install, configure, and detect changes in Chrome extensions programmatically?
    I'm working on a project that allows you to install, configure, and detect changes in Chrome extensions programmatically. I'm using Playwright and the chrome.* API for extension management.

    I'm looking for feedback. I even asked ChatGPT. It said, "Use your brain, you {headless: true}."

    I haven't started coding yet, but you can see my progress on GitHub.

    Here's how it works:

    To install an extension, it creates a preferences file and uses Playwright to enable the extension with the chrome.management.setEnabled method.

    To configure an extension, it uses Playwright to set the configuration values with the chrome.storage.sync.set method and other methods as needed.

    To detect changes in an extension, it uses Playwright to get the extension ID with the chrome.management.getAll method. Then, it uses Playwright to listen for changes with the chrome.storage.sync.addListener method and other methods as needed, generating JavaScript code based on the changes. Finally, it uses WebSocket to send the generated code to a logger.
  threshold: 0.6333256959915162
https://www.reddit.com/r/speechrecognition/comments/16b6kd4/247_speechtotext_transcription_tool_wanted/:
  text: |
    24/7 Speech-to-Text Transcription Tool Wanted
    I'm on the hunt for a tool that can record and transcribe my voice 24/7 to vocalize and capture every thought. For years, scientists worked tirelessly to give humans the gift of eternal memory. Now, every time I forget my anniversary, it's clearly on purpose.

    How I'll Use It
    Here are some ways I plan to use the transcriptions:

    Drafting Content: Mainly, I'll use it to draft messages, emails, social posts, documents - you name it!

    LLM Feedback: Another idea is to feed my daily thoughts into a Language Model (LLM) for insights and practical suggestions.

    Auto-Completion: In the long run, I'd love for the LLM to look at my past transcripts and auto-complete what I'm about to say.

    What I'm Looking For
    Here's what I need in this tool:

    Accuracy: It should catch every word I say, almost as good as a human would.

    Speed: It should be quick on its feet - ideally, less than a second's delay.

    Noise Resistance: A little background noise shouldn't throw it off.

    Budget: I'm hoping to keep it under $100/month. But hey, if it boosts my productivity, I might be willing to stretch that a bit.

    Storage: I'd love to keep the transcriptions forever, and the recordings too if it doesn't cost an arm and a leg. No need for the silent bits though. If it could sync up with Dropbox or something similar, that would be super convenient.

    Security: If it uses cloud storage, top-notch security measures like encryption are a must.

    Segmentation: It would be great if it could break up my transcript into manageable chunks. That way, if I switch topics mid-sentence, each topic gets its own segment.

    Integration: It would be awesome if it could work with macOS, Neovim, and Alacritty for drafting text. Something like a Neovim plugin or macOS clipboard integration would be really handy.

    Format: A simple text file with timestamps would do the trick. But hey, the more options, the merrier!

    Local Transcription: I'd prefer if it could transcribe locally, but I'm open to cloud-based solutions if they're more accurate or easier to maintain.

    Accessibility: I should be able to access the transcriptions from my computer. But my computer should not be the recording device.

    Hardware: Something stationary would work best. Maybe an old mobile phone or a Raspberry Pi. If there's wearable tech that can last all day and gives clearer recordings and more accurate transcriptions, I'm all for it!

    Voice Recognition: Ideally, it should only pick up my voice and ignore everyone else's. But if that's not possible, I can make sure no one else is around when I'm using it.

    Offline Use: An offline mode would be a nice bonus. But since I'll mostly be using this at home, it's not a deal-breaker.

    I know there are some privacy concerns with this kind of tool. But since it'll be in my home, I'm not too worried about invading anyone else's privacy.
  threshold: 0.5744444131851197
https://old.reddit.com/r/speechrecognition/comments/186bk2q/looking_for_the_ideal_microphone_for_247/:
  text: |
    Looking for the Ideal Microphone for 24/7 Transcription
    A couple of months ago, I embarked on a journey to find the perfect 24/7 speech-to-text transcription tool. It all started with a simple post on this subreddit. Now, I've got a question I'm hoping you can help with: What's the ideal microphone for this task? I'm all ears for feedback!

    The biggest hurdle has been finding the right microphone. I have two main requirements: it needs to be comfortable enough to wear all day and precise enough to isolate and transcribe my voice.

    u/Economics-Regular suggested an ear bone microphone, which sounds fascinating. But it seems that most ear bone mics are designed for military use, and they require a radio system to connect. I'm not sure if there is a consumer-friendly option that offers the same convenience as a standard headset, such as Bluetooth connectivity to a computer or phone.

    I've put more than a dozen microphones to the test, and the Poly Voyager 5200 came out on top. However, it's not without its flaws:

    Insufficient Noise Cancellation: It still picks up some background noise, especially loud announcements.
    Excessive Noise Cancellation: It sometimes cancels out my voice when I'm in a small enclosed space.
    Connectivity: There are occasional connectivity issues.
    Battery Life: It only lasts for 7 hours.
    Charging Port: It uses an old Micro USB instead of USB-C.
    Aside from the microphone hunt, I'm also exploring speaker verification. u/rdesh26 recommended the pre-trained ECAPA-TDNN model from SpeechBrain, which looks promising. However, this isn't a replacement for a high-quality microphone.

    I've also created a proof of concept. I have two branches:

    Main Branch: You can try this software, but it's very buggy.
    Develop Branch: This branch is my next rewrite and it's not working yet. Your feedback on this branch will help me improve this software.
    My hope is that by sharing this early-stage concept, it might spark collaborative improvements. Whether it's refining this tool or exploring a completely new approach, I'd love to team up if you're working on something similar or have insights to share.
  threshold: 0.5510760545730592
https://old.reddit.com/r/HeadphoneAdvice/comments/18pfkgu/looking_for_a_headset_that_can_handle_247/:
  text: |
    Looking for a Headset that Can Handle 24/7 Transcription: OpenComm 2, You're Almost There
    I've been working on a project to transcribe everything I say, all day, every day. You can check out the project goals.

    For that, I need the perfect headset: comfortable enough for all-day wear and capable of capturing my voice with crystal clear quality. You can see the headset requirements for more details.

    Do you know any good headsets that fit the bill?

    Just to give you an idea, I'm not shy about shelling out a grand if it's the right gear. At first, I spent a lot on a fancy Shure headset. My partner said, "I'm sure that was a sound investment." I said, "Sure, if only it could cancel all the noise you make!"

    Currently, I'm leaning toward Shokz's OpenComm 2. But it's not quite there yet. Here's why:

    Background Noise: Its mic struggles with background noise, especially loud announcements. The Poly Voyager 5200 did better. I tested them with some noise at arm's length. Voyager barely picked it up, but OpenComm 2 did.
    Voice Chat: Discord voice chat doesn't work at all.
    Multiple Device Connectivity: The ability to connect multiple devices and transmit audio signals simultaneously would be a game-changer. Sadly, OpenComm 2 doesn't support this.
    Reconnection: It doesn't automatically reconnect to my Mac when it comes back into range.
    Wind Noise: The Poly Voyager 5200's mic handles wind noise better. I tested them by holding them near an air conditioner. The Voyager didn't pick up much wind noise, but the OpenComm 2 did, sometimes as loud as my voice. I don't want to use a windscreen, because that's too much hassle.
    Muting: The mic doesn't auto-mute when I move the boom up.
    Comfort: It's mostly comfortable, but it starts to bother me after wearing it for a while.
    Charging: "The headset will automatically shut down when charging." This feature seems to be non-configurable.
    Charging Cable: I get the proprietary charging port for waterproofing, but using outdated USB-A instead of USB-C is a bummer.
    Audio Quality: I've noticed the sound starts to crackle even at medium volume.
    Playback Button: Ideally, double-clicking should skip to the next track, and triple-clicking should go back one. But this doesn't work with YouTube or Dropbox.
    Battery Display: The headset's battery level is visible when it's connected to my Mac via Bluetooth, but not when using a USB-C dongle. Plus, it's impossible to check my iPhone's battery level. Ideally, both my Mac and iPhone would display the headset's battery level consistently, just like they do for their batteries.
    So, I'm still looking for a better headset. Any leads would be appreciated!
  threshold: 0.6778861284255982
https://old.reddit.com/r/slp/comments/193p53j/looking_for_a_tool_for_filler_word_analysis/:
  text: |
    Looking for a Tool for Filler Word Analysis
    I'm working on a personal project to improve my spoken language skills. I've created an open-source tool that transcribes everything I say 24/7. My transcript revealed that "uh" and "huh" are my most frequent fillers. It was an "uh-huh" moment!

    My goal now is to reduce the filler words I use.

    I thought of making another tool to count and analyze filler words.

    Does anyone know if there is something like this already, or a better way that experts in speech-language pathology would recommend? If it exists, I could just use it and save some time.

    Filler Word Analysis: The tool should tally up common filler words and provide their frequency.
    Baseline Comparison: It should compare my filler word usage with standard linguistic data (like Google's n-gram dataset) to determine if I'm above or below the norm.
    Sorting: The tool should rank filler words based on how much their frequency surpasses the baseline.
    Local Operation: The tool should operate locally to ensure privacy, as the transcripts are raw and unfiltered.
    User Interface: I like a command line interface that takes a text file as input and can also read from standard input. But hey, a graphical user interface could work too.
    Any suggestion is appreciated.
  threshold: 0.5055704116821290
