https://www.reddit.com/r/socialmedia/comments/10z01nv/best_social_media_listening_tools/:
  text: |
    Best Social Media Listening Tools
    Professional Discussion
    I kinda feel like social media listening tools in the market are popping up in the market everyday & demand is also increasing. These are my favourite tools for social listening:

    1. Mention
    It’s one of the most used social listening tool as I always come across this tool in a conversation about social listening.

    Overall the tool is recommended by me because the resources & features they provide can help you better than other tools in the market.

    2. Brandwatch
    Brandwatch is a social media management tool, but they acquired Falcon, A social listening tool. Now, it’s the part of their platform and you can schedule & listen to your audience within their platform.

    One of the reasons I recommend them is they do great job at CX & collaborate well with HigherEd. If you work in HigherEd, I will recommend you to go for Brandwatch.

    3. Syften
    Syften can help you track conversations around your product & business on reddit, quora, hacker news & others.

    I don’t dislike the tool, but it’s best for SaaS owners, startups. It’s a scrappy social listening tool but it works. That’s why I mentioned it here.

    4. Brand 24
    Brand 24 is another great social listening tool with a better reporting process. You can track mentions across all main marketing channels & get reported.

    I myself came across brand24 recently through reddit suggestions. From what I have heard so far. It deserves to be here.

    5. Tweetdeck
    It’s the best tool to track conversations around your brand on Twitter.

    But some features like reporting & better CX isn’t the best part of Tweetdeck. As Twitter isn’t fully focused on users utilising this feature.

    But if your brand audience is active on twitter, this tool can deliver most accurate results.

    6. Gummy Search
    It’s one of the best tool to track conversations across reddit & you can also get analysis of sub-reddits where your target audience is active.

    Recommended to SaaS founders, startups & entrepreneurs to track conversations around their business.

    Honourable mentions
    Agorapulse & Sproutsocial are also famous for social listening but they are overall social media management tools. That’s why you might consider moving to them completely if your current tool lacks social listening features.

    Awario is a social listening tool with similar features to tools mentioned above but not a standout. That’s why it didn’t make the list.

    Google Alerts is one of my favourites but the tracking is limited to Google only.

    Thanks for reading. You can share your favourite social listening tool below & join r/marketingcurated for more tools & resource suggestions.
  threshold: 0.5856844186782838
https://www.reddit.com/r/mac/comments/13d9rfd/monitoring_plist_changes_and_generating/:
  text: |
    Monitoring plist changes and generating `PlistBuddy` commands
    Question
    I am looking for a tool or method to monitor plist changes on my Mac and generate the corresponding PlistBuddy commands when preferences are changed in macOS or apps. I want to avoid using defaults write since some preference values are nested. (Plists are like onions, they have layers upon layers, and just when you think you've peeled them all, another one appears to make you cry.)

    I've found these repositories, but they don't exactly do what I want:

    macos-defaults

    plistwatch

    My ideal workflow is as follows:

    Start the monitoring tool.

    Change preferences in macOS or apps.

    The tool shows PlistBuddy commands.

    Copy and paste the commands into my setup script.

    This would be similar to how Karabiner-EventViewer works for a different problem.

    Any suggestions on how to achieve this or existing tools that can help me with this workflow?
  threshold: 0.3411819338798524
https://www.reddit.com/r/selfhosted/comments/13tkasa/seeking_advice_on_developing_a_selfhosted_tool/:
  text: |
    Seeking advice on developing a self-hosted tool for monitoring and notifying users of relevant social media comments
    Hello r/selfhosted community,

    I'm about to embark on a journey of self-loathing, er, self-hosting, and I could use your advice. I'm working on a tool that monitors and notifies users of relevant social media comments related to a specific product using natural language processing and machine learning techniques. The draft of the documentation is available here.

    "Self-hosting? More like self-loathing because it's like being your own customer service representative, except the customer is an idiot, and that idiot is you." But I'm willing to take on the challenge because I want to ensure the tool is suitable for self-hosting and offers the flexibility and control that comes with it.

    Some of the challenges I'm facing include:

    Ensuring the tool can effectively monitor and analyze comments across various social media platforms.

    Handling potential false positives or negatives in the comment analysis.

    Designing an efficient notification system for users.

    I've recently posted a question on r/LanguageTechnology. However, that post is focused on NLP, and I'd like to shift the focus here to self-hosting aspects.

    I would appreciate any feedback, suggestions, or recommendations from the r/selfhosted community on the self-hosting aspects of this project. Are there any specific aspects you'd like to discuss or any additional features you think would be valuable for this tool?

    Thank you for your time and input!
  threshold: 0.6040834188461305
https://www.reddit.com/r/LanguageTechnology/comments/13sqmks/seeking_advice_on_developing_a_tool_to_monitor/:
  text: |
    Seeking Advice on Developing a Tool to Monitor and Notify Users of Relevant Social Media Comments
    I have been working on a tool that aims to monitor and notify users of relevant social media comments related to a specific product. I have documented my thoughts and ideas for this tool in this GitHub repository. The tool uses natural language processing and machine learning techniques to find and notify users of similar Reddit posts.

    I would like to ask for advice on the following aspects:

    Are there any existing tools or approaches that can help me with this task, or if there are any suggestions for how to effectively use NLP and machine learning techniques for this purpose?

    Any insights or resources related to NLP and machine learning in the context of social media monitoring would be greatly appreciated.

    They say NLP can predict our behavior. If only it could predict my next terrible joke, I'd save so much embarrassment.

    Please feel free to review the documentation and provide any feedback or suggestions. Thank you!
  threshold: 0.5384714603424073
https://www.reddit.com/r/chrome_extensions/comments/15074p2/how_do_you_install_configure_and_detect_changes/:
  text: |
    How do you install, configure, and detect changes in Chrome extensions programmatically?
    I'm working on a project that allows you to install, configure, and detect changes in Chrome extensions programmatically. I'm using Playwright and the chrome.* API for extension management.

    I'm looking for feedback. I even asked ChatGPT. It said, "Use your brain, you {headless: true}."

    I haven't started coding yet, but you can see my progress on GitHub.

    Here's how it works:

    To install an extension, it creates a preferences file and uses Playwright to enable the extension with the chrome.management.setEnabled method.

    To configure an extension, it uses Playwright to set the configuration values with the chrome.storage.sync.set method and other methods as needed.

    To detect changes in an extension, it uses Playwright to get the extension ID with the chrome.management.getAll method. Then, it uses Playwright to listen for changes with the chrome.storage.sync.addListener method and other methods as needed, generating JavaScript code based on the changes. Finally, it uses WebSocket to send the generated code to a logger.
  threshold: 0.6333256959915162
https://www.reddit.com/r/socialmedia/comments/15kbryt/the_best_social_media_content_discovery_tool/:
  text: |
    The Best Social Media content discovery tool
    Professional Discussion
    Hi,

    I'm looking for a tool to use that helps us find relevant content from others on social media platforms in order to interact with them. An example usecase for us is;

    We search for the hashtag #procurement and find people who are posting about this on Twitter. And from the app we can respond directly via our connected account.

    We've been trying out Tweethunter briefly but it's only Twitter and it's not doing amazing.

    Is anybody are of such a tool? Thank you!
  threshold: 0.5693426132202149
